import 'package:flutter/material.dart';
import 'NewsScreen.dart';

class HomeScreen extends StatefulWidget {
  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  bool isArabic = true;

  /// Arabic topics
  final List<String> allTopicsAr = [
    'الرياضة',
    'التكنولوجيا',
    'السياسة',
    'الاقتصاد',
    'الصحة',
    'العلوم',
    'الفن',
    'الأدب',
    'التعليم',
    'التاريخ',
    'الطبيعة',
    'السفر',
    'الطعام',
    'الأزياء',
    'السيارات',
    'الموسيقى',
    'الأفلام',
    'الألعاب',
    'الفضاء',
    'الطقس',
    'الطاقة',
    'القانون',
    'الهندسة',
    'الزراعة',
    'البيئة',
    'اللغات',
    'التجارة',
    'التصميم',
    'التسويق',
    'التصوير',
    'التدريب',
    'البرمجة',
    'الذكاء الاصطناعي',
    'الأمن السيبراني',
    'الابتكار',
    'المسرح',
    'الشعر',
    'الكتب',
    'العملات',
    'المناخ',
    'الفلسفة',
    'الدين',
    'المعارض',
    'الاحتفالات',
    'الأحياء',
    'الكيمياء',
    'الفيزياء',
    'الرياضيات',
    'الطب',
    'طب الأسنان',
    'التمريض',
    'اللياقة البدنية',
    'التغذية',
    'العقارات',
    'البورصة',
    'العمل الخيري',
    'التطوع',
    'التصنيع',
    'البحرية',
    'الطيران',
    'القطارات',
    'الموانئ',
    'الطاقة المتجددة',
    'النفط والغاز',
    'المياه',
    'البرية',
    'الحيوانات',
    'الطيور',
    'الحشرات',
    'الأحياء البحرية',
    'الزهور',
    'الأشجار',
    'المحميات الطبيعية',
    'الطبخ',
    'الحلويات',
    'المشروبات',
    'القهوة',
    'الشاي',
    'العصائر',
    'العمارة',
    'المتاحف',
    'الآثار',
    'الكتب المصورة',
    'المجلات',
    'الصحف',
    'الإذاعة',
    'التلفزيون',
    'البودكاست',
    'المهرجانات',
    'السباقات',
    'البطولات',
    'الألعاب الإلكترونية',
    'الروبوتات',
    'الطباعة ثلاثية الأبعاد',
    'الشبكات',
    'البرمجيات',
    'الأجهزة',
    'التطبيقات',
  ];

  /// English topics
  final List<String> allTopicsEn = [
    'Sports',
    'Technology',
    'Politics',
    'Economy',
    'Health',
    'Science',
    'Art',
    'Literature',
    'Education',
    'History',
    'Nature',
    'Travel',
    'Food',
    'Fashion',
    'Cars',
    'Music',
    'Movies',
    'Games',
    'Space',
    'Weather',
    'Energy',
    'Law',
    'Engineering',
    'Agriculture',
    'Environment',
    'Languages',
    'Commerce',
    'Design',
    'Marketing',
    'Photography',
    'Training',
    'Programming',
    'Artificial Intelligence',
    'Cybersecurity',
    'Innovation',
    'Theatre',
    'Poetry',
    'Books',
    'Currencies',
    'Climate',
    'Philosophy',
    'Religion',
    'Exhibitions',
    'Celebrations',
    'Biology',
    'Chemistry',
    'Physics',
    'Mathematics',
    'Medicine',
    'Dentistry',
    'Nursing',
    'Fitness',
    'Nutrition',
    'Real Estate',
    'Stock Market',
    'Charity',
    'Volunteering',
    'Manufacturing',
    'Maritime',
    'Aviation',
    'Trains',
    'Ports',
    'Renewable Energy',
    'Oil & Gas',
    'Water',
    'Wildlife',
    'Animals',
    'Birds',
    'Insects',
    'Marine Life',
    'Flowers',
    'Trees',
    'Nature Reserves',
    'Cooking',
    'Desserts',
    'Drinks',
    'Coffee',
    'Tea',
    'Juices',
    'Architecture',
    'Museums',
    'Antiquities',
    'Comics',
    'Magazines',
    'Newspapers',
    'Radio',
    'Television',
    'Podcasts',
    'Festivals',
    'Races',
    'Tournaments',
    'E-sports',
    'Robotics',
    '3D Printing',
    'Networks',
    'Software',
    'Hardware',
    'Applications',
  ];

  /// Icon mapping
  final Map<String, IconData> topicIcons = {
    'الرياضة': Icons.sports_soccer,
    'Sports': Icons.sports_soccer,
    'التكنولوجيا': Icons.memory,
    'Technology': Icons.memory,
    'السياسة': Icons.gavel,
    'Politics': Icons.gavel,
    'الاقتصاد': Icons.account_balance,
    'Economy': Icons.account_balance,
    'الصحة': Icons.health_and_safety,
    'Health': Icons.health_and_safety,
    'العلوم': Icons.science,
    'Science': Icons.science,
    'الفن': Icons.brush,
    'Art': Icons.brush,
    'الأدب': Icons.menu_book,
    'Literature': Icons.menu_book,
    'التعليم': Icons.school,
    'Education': Icons.school,
    'التاريخ': Icons.history_edu,
    'History': Icons.history_edu,
    'الطبيعة': Icons.landscape,
    'Nature': Icons.landscape,
    'السفر': Icons.flight_takeoff,
    'Travel': Icons.flight_takeoff,
    'الطعام': Icons.restaurant,
    'Food': Icons.restaurant,
    'الأزياء': Icons.checkroom,
    'Fashion': Icons.checkroom,
    'السيارات': Icons.directions_car,
    'Cars': Icons.directions_car,
    'الموسيقى': Icons.music_note,
    'Music': Icons.music_note,
    'الأفلام': Icons.movie,
    'Movies': Icons.movie,
    'الألعاب': Icons.videogame_asset,
    'Games': Icons.videogame_asset,
    'الفضاء': Icons.public,
    'Space': Icons.public,
    'الطقس': Icons.cloud,
    'Weather': Icons.cloud,
    'الطاقة': Icons.bolt,
    'Energy': Icons.bolt,
    'القانون': Icons.balance,
    'Law': Icons.balance,
    'الهندسة': Icons.engineering,
    'Engineering': Icons.engineering,
    'الزراعة': Icons.agriculture,
    'Agriculture': Icons.agriculture,
    'البيئة': Icons.eco,
    'Environment': Icons.eco,
    'اللغات': Icons.translate,
    'Languages': Icons.translate,
    'التجارة': Icons.shopping_bag,
    'Commerce': Icons.shopping_bag,
    'التصميم': Icons.design_services,
    'Design': Icons.design_services,
    'التسويق': Icons.campaign,
    'Marketing': Icons.campaign,
    'التصوير': Icons.camera_alt,
    'Photography': Icons.camera_alt,
    'التدريب': Icons.fitness_center,
    'Training': Icons.fitness_center,
    'البرمجة': Icons.code,
    'Programming': Icons.code,
    'الذكاء الاصطناعي': Icons.smart_toy,
    'Artificial Intelligence': Icons.smart_toy,
    'الأمن السيبراني': Icons.security,
    'Cybersecurity': Icons.security,
    'الابتكار': Icons.lightbulb,
    'Innovation': Icons.lightbulb,
    'المسرح': Icons.theaters,
    'Theatre': Icons.theaters,
    'الشعر': Icons.format_quote,
    'Poetry': Icons.format_quote,
    'الكتب': Icons.book,
    'Books': Icons.book,
    'العملات': Icons.currency_exchange,
    'Currencies': Icons.currency_exchange,
    'المناخ': Icons.thermostat,
    'Climate': Icons.thermostat,
    'الفلسفة': Icons.psychology,
    'Philosophy': Icons.psychology,
    'الدين': Icons.mosque,
    'Religion': Icons.mosque,
    'المعارض': Icons.store,
    'Exhibitions': Icons.store,
    'الاحتفالات': Icons.celebration,
    'Celebrations': Icons.celebration,
    'الأحياء': Icons.biotech,
    'Biology': Icons.biotech,
    'الكيمياء': Icons.science,
    'Chemistry': Icons.science,
    'الفيزياء': Icons.auto_graph,
    'Physics': Icons.auto_graph,
    'الرياضيات': Icons.calculate,
    'Mathematics': Icons.calculate,
    'الطب': Icons.local_hospital,
    'Medicine': Icons.local_hospital,
    'طب الأسنان': Icons.medical_services,
    'Dentistry': Icons.medical_services,
    'التمريض': Icons.healing,
    'Nursing': Icons.healing,
    'اللياقة البدنية': Icons.fitness_center,
    'Fitness': Icons.fitness_center,
    'التغذية': Icons.restaurant_menu,
    'Nutrition': Icons.restaurant_menu,
    'العقارات': Icons.apartment,
    'Real Estate': Icons.apartment,
    'البورصة': Icons.show_chart,
    'Stock Market': Icons.show_chart,
    'العمل الخيري': Icons.volunteer_activism,
    'Charity': Icons.volunteer_activism,
    'التطوع': Icons.handshake,
    'Volunteering': Icons.handshake,
    'التصنيع': Icons.precision_manufacturing,
    'Manufacturing': Icons.precision_manufacturing,
    'البحرية': Icons.directions_boat,
    'Maritime': Icons.directions_boat,
    'الطيران': Icons.flight,
    'Aviation': Icons.flight,
    'القطارات': Icons.train,
    'Trains': Icons.train,
    'الموانئ': Icons.anchor,
    'Ports': Icons.anchor,
    'الطاقة المتجددة': Icons.solar_power,
    'Renewable Energy': Icons.solar_power,
    'النفط والغاز': Icons.local_gas_station,
    'Oil & Gas': Icons.local_gas_station,
    'المياه': Icons.water_drop,
    'Water': Icons.water_drop,
    'البرية': Icons.park,
    'Wildlife': Icons.park,
    'الحيوانات': Icons.pets,
    'Animals': Icons.pets,
    'الطيور': Icons.cruelty_free,
    'Birds': Icons.cruelty_free,
    'الحشرات': Icons.bug_report,
    'Insects': Icons.bug_report,
    'الأحياء البحرية': Icons.scuba_diving,
    'Marine Life': Icons.scuba_diving,
    'الزهور': Icons.local_florist,
    'Flowers': Icons.local_florist,
    'الأشجار': Icons.nature,
    'Trees': Icons.nature,
    'المحميات الطبيعية': Icons.forest,
    'Nature Reserves': Icons.forest,
    'الطبخ': Icons.kitchen,
    'Cooking': Icons.kitchen,
    'الحلويات': Icons.icecream,
    'Desserts': Icons.icecream,
    'المشروبات': Icons.local_drink,
    'Drinks': Icons.local_drink,
    'القهوة': Icons.coffee,
    'Coffee': Icons.coffee,
    'الشاي': Icons.local_cafe,
    'Tea': Icons.local_cafe,
    'العصائر': Icons.blender,
    'Juices': Icons.blender,
    'العمارة': Icons.apartment,
    'Architecture': Icons.apartment,
    'المتاحف': Icons.museum,
    'Museums': Icons.museum,
    'الآثار': Icons.account_balance,
    'Antiquities': Icons.account_balance,
    'الكتب المصورة': Icons.menu_book,
    'Comics': Icons.menu_book,
    'المجلات': Icons.book_online,
    'Magazines': Icons.book_online,
    'الصحف': Icons.article,
    'Newspapers': Icons.article,
    'الإذاعة': Icons.radio,
    'Radio': Icons.radio,
    'التلفزيون': Icons.tv,
    'Television': Icons.tv,
    'البودكاست': Icons.podcasts,
    'Podcasts': Icons.podcasts,
    'المهرجانات': Icons.festival,
    'Festivals': Icons.festival,
    'السباقات': Icons.flag,
    'Races': Icons.flag,
    'البطولات': Icons.emoji_events,
    'Tournaments': Icons.emoji_events,
    'الألعاب الإلكترونية': Icons.sports_esports,
    'E-sports': Icons.sports_esports,
    'الروبوتات': Icons.smart_toy,
    'Robotics': Icons.smart_toy,
    'الطباعة ثلاثية الأبعاد': Icons.print,
    '3D Printing': Icons.print,
    'الشبكات': Icons.wifi,
    'Networks': Icons.wifi,
    'البرمجيات': Icons.developer_mode,
    'Software': Icons.developer_mode,
    'الأجهزة': Icons.devices,
    'Hardware': Icons.devices,
    'التطبيقات': Icons.apps,
    'Applications': Icons.apps,
  };

  String searchQuery = '';

  @override
  Widget build(BuildContext context) {
    final topics = isArabic ? allTopicsAr : allTopicsEn;
    final filteredTopics =
        topics
            .where(
              (topic) =>
                  topic.toLowerCase().contains(searchQuery.toLowerCase()),
            )
            .toList();

    return Directionality(
      textDirection: isArabic ? TextDirection.rtl : TextDirection.ltr,
      child: Scaffold(
        appBar: AppBar(
          title: Text(isArabic ? 'مواضيع الأخبار' : 'News Topics'),
          actions: [
            IconButton(
              icon: Icon(Icons.language),
              tooltip: isArabic ? 'Switch to English' : 'التبديل إلى العربية',
              onPressed: () {
                setState(() {
                  isArabic = !isArabic;
                  searchQuery = '';
                });
              },
            ),
          ],
        ),
        body: Column(
          children: [
            Padding(
              padding: EdgeInsets.all(12.0),
              child: TextField(
                decoration: InputDecoration(
                  fillColor: Colors.teal[100],
                  filled: true,
                  hintText:
                      isArabic ? 'ابحث عن المواضيع...' : 'Search topics...',
                  hintStyle: TextStyle(color: Colors.teal[900]),
                  prefixIcon: Icon(Icons.search, color: Colors.teal[800]),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(25),
                  ),
                ),
                onChanged: (value) {
                  setState(() {
                    searchQuery = value;
                  });
                },
              ),
            ),
            Expanded(
              child: GridView.builder(
                padding: EdgeInsets.all(12),
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 2,
                  crossAxisSpacing: 12,
                  mainAxisSpacing: 12,
                  childAspectRatio: 3,
                ),
                itemCount: filteredTopics.length,
                itemBuilder: (context, index) {
                  final topic = filteredTopics[index];
                  final icon = topicIcons[topic] ?? Icons.article;
                  return GestureDetector(
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder:
                              (_) =>
                                  NewsScreen(query: topic, isArabic: isArabic),
                        ),
                      );
                    },
                    child: Container(
                      decoration: BoxDecoration(
                        color: Colors.teal[100],
                        borderRadius: BorderRadius.circular(25),
                      ),
                      padding: EdgeInsets.symmetric(horizontal: 12),
                      child: Row(
                        children: [
                          Icon(icon, size: 26, color: Colors.teal[800]),
                          SizedBox(width: 10),
                          Expanded(
                            child: Text(
                              topic,
                              style: TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.w500,
                                color: Colors.teal[900],
                              ),
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
